---
- name: "Deploy de Novas VMs no Proxmox (com ID Automático)"
  hosts: localhost
  gather_facts: false

  # As variáveis de entrada do usuário (Survey Variables)
  # - vm_count
  # - vm_name_prefix
  # - template_name

  pre_tasks:
    - name: "Descobrir o próximo VMID livre"
      # 1. Busca fatos de todas as VMs existentes
      community.general.proxmox_facts:
        api_user: "{{ lookup('env', 'proxmox_api_user') }}"
        api_password: "{{ lookup('env', 'proxmox_api_secret') }}"
        api_host: "{{ lookup('env', 'proxmox_api_host') }}"
      register: proxmox_info

    - name: "Calcular o próximo VMID"
      # 2. Lógica para encontrar o próximo ID
      ansible.builtin.set_fact:
        # Define um range inicial para as novas VMs (ex: a partir de 700)
        vmid_range_start: 700
        # Pega a lista de todos os IDs de VM existentes
        existing_vmids: "{{ proxmox_info.proxmox_vms | map(attribute='vmid') | list }}"
        # Calcula o próximo ID: pega o maior ID dentro do nosso range e soma 1.
        # Se nenhuma VM existir no range, começa com o vmid_range_start.
        next_vmid: "{{ (existing_vmids | select('>=', vmid_range_start) | max | default(vmid_range_start - 1)) + 1 }}"

  tasks:
    - name: "1. Clonar, configurar e ligar as VMs em paralelo"
      community.general.proxmox_kvm:
        api_user: "{{ lookup('env', 'proxmox_api_user') }}"
        api_password: "{{ lookup('env', 'proxmox_api_secret') }}"
        api_host: "{{ lookup('env', 'proxmox_api_host') }}"
        node: "pve-main" # Mude se o nome do seu node for outro
        
        # USA A VARIÁVEL CALCULADA AUTOMATICAMENTE!
        vmid: "{{ next_vmid | int + item }}"
        name: "{{ vm_name_prefix }}-{{ item + 1 }}"
        clone: "{{ template_name }}"
        
        cores: 2
        memory: 2048
        
        state: started
        timeout: 300
      
      loop: "{{ range(0, vm_count | int) | list }}"
      register: vm_creation_results

    - name: "2. Adicionar novas VMs ao inventário em memória"
      ansible.builtin.add_host:
        name: "{{ item.invocation.module_args.name }}"
        groups: novas_vms
      loop: "{{ vm_creation_results.results }}"
      loop_control:
        label: "{{ item.invocation.module_args.name }}"

- name: "Configurar as VMs recém-criadas"
  hosts: novas_vms
  gather_facts: no
  
  tasks:
    - name: "3. Aguardar o SSH estar disponível"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "4. Mudar o hostname dentro da VM"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true