---
- name: "PLAY 1: Provisionar infraestrutura no Proxmox"
  hosts: localhost
  gather_facts: false
  
  vars:
    # Estas variáveis serão preenchidas pelas 'Survey Variables' do Semaphore
    # - vm_count
    # - vm_name_prefix
    # - template_name
    proxmox_node_name: "pve-main" # Defina aqui o nome do seu node Proxmox

  tasks:
    - name: "Executar a role 'deploy-vm' para criar as máquinas"
      ansible.builtin.include_role:
        name: "roles/deploy-vm"
      # Executa a role uma vez para cada VM a ser criada
      loop: "{{ range(0, vm_count | int) | list }}"


- name: "PLAY 2: Configurar as VMs recém-criadas"
  hosts: novas_vms # Alvo são as VMs que acabamos de adicionar em memória
  gather_facts: false
  
  tasks:
    - name: "Aguardar o SSH estar disponível"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "Coletar fatos das novas VMs"
      ansible.builtin.gather_facts:

    - name: "Definir o hostname dentro da VM"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true

    - name: "Enviar notificação final (exemplo)"
      ansible.builtin.debug:
        msg: |
          VM '{{ inventory_hostname }}' criada com sucesso!
          IP: {{ ansible_default_ipv4.address }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      delegate_to: localhost