---
- name: "Deploy de Novas VMs no Proxmox"
  hosts: localhost
  gather_facts: false

  tasks:
    - name: "1. Clonar, configurar e ligar as VMs em paralelo"
      community.general.proxmox_kvm:
        api_user: "{{ lookup('env', 'proxmox_api_user') }}"
        api_password: "{{ lookup('env', 'proxmox_api_secret') }}"
        api_host: "{{ proxmox_api_host }}" 
        node: "pve-main"
        
        vmid: "{{ vmid_start | int + item }}"
        name: "{{ vm_name_prefix }}-{{ item + 1 }}"
        clone: "{{ template_name }}"
        
        cores: 2
        memory: 2048 # em MB
        
        state: started
        timeout: 300
      
      loop: "{{ range(0, vm_count | int) | list }}"
      register: vm_creation_results

    - name: "2. Adicionar novas VMs ao inventário em memória"
      ansible.builtin.add_host:
        name: "{{ item.invocation.module_args.name }}"
        groups: novas_vms
      loop: "{{ vm_creation_results.results }}"
      loop_control:
        label: "{{ item.invocation.module_args.name }}"

- name: "Configurar as VMs recém-criadas"
  hosts: novas_vms
  gather_facts: no
  
  tasks:
    - name: "3. Aguardar o SSH estar disponível"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "4. Mudar o hostname dentro da VM"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true 