---
- name: "PLAY 1: Provisionar infraestrutura no Proxmox"
  hosts: localhost
  gather_facts: false
  
  vars:
    proxmox_node_name: "pve-main"

  tasks:
    - name: "Executar a role 'deploy-vm' para criar as máquinas"
      ansible.builtin.include_role:
        name: "roles/deploy-vm"
      # Passa a variável 'item' do loop para a role com o nome 'loop_index'
      vars:
        loop_index: "{{ item }}"
      loop: "{{ range(0, vm_count | int) | list }}"
      register: creation_results

    - name: "Adicionar todas as novas VMs ao grupo 'novas_vms'"
      ansible.builtin.add_host:
        name: "{{ item.invocation.module_args.name }}"
        groups: novas_vms
        ansible_host: "{{ item.ansible_facts.ip_address }}"
      # Ajuste no loop para extrair os dados corretamente
      loop: "{{ creation_results.results }}"
      when: item.ansible_facts.ip_address is defined

- name: "PLAY 2: Configurar as VMs recém-criadas"
  hosts: novas_vms # Agora este grupo terá os servidores corretos
  gather_facts: false
  
  tasks:
    - name: "Aguardar o SSH estar disponível"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "Coletar fatos das novas VMs"
      ansible.builtin.gather_facts:

    - name: "Definir o hostname dentro da VM"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      become: true

    - name: "VM Criada com Sucesso!"
      ansible.builtin.debug:
        msg: |
          VM '{{ inventory_hostname }}' provisionada e configurada!
          IP: {{ ansible_default_ipv4.address }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      delegate_to: localhost