---
- name: "Provisionar e Configurar VMs no ProxMox"
  hosts: localhost
  gather_facts: false
  
  vars:
    # --- VARIÁVEIS DE CONFIGURAÇÃO PADRÃO ---
    proxmox_node_name: "pve-main"
    vmid_range_start: 700
    # ... (o resto das suas vars) ...
    default_vm_password: "ijo1Epaing5"
    
  pre_tasks:
    - name: "FORÇAR Instalação da dependência Python 'proxmoxer'"
      ansible.builtin.pip:
        name: proxmoxer
        state: present
      delegate_to: localhost # Garante que rode dentro do container do AWX

  tasks:
    - name: "Descobrir o próximo VMID livre"
      community.proxmox.proxmox_vm_info:
        api_user: "{{ lookup('env','PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env','PROXMOX_API_PASS') }}"
        api_host: "{{ lookup('env','PROXMOX_API_HOST') }}"
      register: proxmox_info

    - name: "Calcular o próximo VMID disponível"
      ansible.builtin.set_fact:
        existing_vmids: "{{ proxmox_info.vms | map(attribute='vmid') | list }}"
        next_vmid: "{{ (existing_vmids | select('>=', vmid_range_start) | max | default(vmid_range_start - 1)) + 1 }}"

    - name: "[CRIAR] Clonar e configurar a VM {{ vm_name_prefix }}-{{ item + 1 }}"
      # CORREÇÃO: Usando a nova coleção community.proxmox
      community.proxmox.proxmox_kvm:
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASS') }}"
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        node: "{{ proxmox_node_name }}"
        vmid: "{{ next_vmid | int + item }}"
        name: "{{ vm_name_prefix }}-{{ item + 1 }}"
        clone: "{{ template_name }}"
        cores: "{{ default_vm_cores }}"
        memory: "{{ default_vm_memory }}"
        ciuser: "{{ default_vm_user }}"
        cipassword: "{{ default_vm_password }}"
        ipconfig0: "ip=dhcp"
        state: started
        timeout: 300
      loop: "{{ range(0, vm_count | int) | list }}"
      register: creation_results

    - name: "Adicionar novas VMs ao grupo 'novas_vms' em memória"
      ansible.builtin.add_host:
        name: "{{ item.invocation.module_args.name }}"
        groups: novas_vms
        # CORREÇÃO: O IP é retornado em 'item.ip_address', não em 'item.ansible_facts'
        ansible_host: "{{ item.ip_address }}"
      loop: "{{ creation_results.results }}"
      # CORREÇÃO: Condição baseada no caminho correto da variável
      when: item.ip_address is defined

- name: "PLAY 2: Configurar as VMs recém-criadas"
  hosts: novas_vms
  gather_facts: true
  become: true
  
  tasks:
    - name: "Aguardar o SSH estar disponível"
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300

    - name: "Definir o hostname dentro da VM"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: "VM Criada com Sucesso!"
      ansible.builtin.debug:
        msg: |
          VM '{{ inventory_hostname }}' provisionada e configurada!
          IP: {{ ansible_default_ipv4.address }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      delegate_to: localhost
      become: false